### PR TITLE
Fix package compiler and regular builds

### LINKED ISSUE #253: PackageCompiler failing: `no method matching rand(::Int64)`
Seems to be caused by recent changes in PreallocationTools.jl, where `rand` is now used.
https://github.com/SciML/PreallocationTools.jl/commit/b0c743c279c1d0c4ef2e2a51dca3ca9292007444

### PR DESCRIPTION
**Pull request by benegee**
~~Add `PreallocationTools = "< 0.4.30"` compat.~~

Use `filter_stdlibs = false` (thanks to @vchuravy )
(we found in #216 that the resulting shared object is large anyways)
Resolves #253 

Use `Trixi.False() ` instead of `OrdinaryDiffEq.False()`.

### CODE REVIEW

File: LibTrixi.jl/lib/build.jl [hunk 1]
```diff
@@ -43,7 +43,7 @@ lib_name = "trixi"
 incremental = false
 
 # Do not include stdlibs which are not needed
-filter_stdlibs = true
+filter_stdlibs = false
```
Comment (sloede) [inline LibTrixi.jl/lib/build.jl:46]: Wouldn't the "correct" fix be to add `Random` explicitly to the `Project.toml`?

**Review by sloede — APPROVED** [review]
LGTM!
